version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3001
      SOLR_URL: solr:8983
      SOLR_COLLECTION: twitterCollection
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - backend

  solr:
    image: "solr:8"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core twitterCollection; exec solr -f"
    ports:
      - "8983:8983"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
